name: rmqgo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  APP_ENV: ${{ secrets.APP_ENV }}
  RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
  RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST }}
  RABBITMQ_PASS: ${{ secrets.RABBITMQ_PASS }}
  RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}

jobs:
  audit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ["1.22.x"]
        os: [ubuntu-latest]

    services:
      rabbitmq:
        image: rabbitmq
        env:
          APP_ENV: ${{ env.APP_ENV }}
          RABBITMQ_DEFAULT_USER: ${{ env.RABBITMQ_USER }}
          RABBITMQ_DEFAULT_PASS: ${{ env.RABBITMQ_PASS }}
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install rmqgo dependencies
        run: make install

      - name: Build rmqgo
        run: make build

      - name: Run rmqgo tests
        run: make test
        env:
          APP_ENV: ${{ env.APP_ENV }}
          RABBITMQ_HOST: ${{ env.RABBITMQ_HOST }}
          RABBITMQ_USER: ${{ env.RABBITMQ_USER }}
          RABBITMQ_PASS: ${{ env.RABBITMQ_PASS }}
          RABBITMQ_PORT: ${{ env.RABBITMQ_PORT }}
